# Generated by Django 4.2 on 2023-04-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsc', '0002_mainwebs_url_alter_mainwebs_total_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainwebs',
            name='user',
        ),
    ]
