# Generated by Django 4.2 on 2023-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsc', '0003_remove_mainwebs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwebs',
            name='name',
            field=models.CharField(blank=True, default='in progress', null=True),
        ),
    ]
